# Site settings
title: Joel's Blog
email: blog@joelwilliamson.ca
description: > # this means to ignore newlines until "baseurl:"
  A blog about whatever strikes my fancy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.joelwilliamson.ca" # the base hostname & protocol for your site
github_username:  joelwilliamson

# Build settings
markdown: redcarpet

#kramdown:
#        input: GFM

redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
